apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nogoo-mcp
  namespace: nogoo9
spec:
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nogoo-mcp
                port:
                  number: 3000
