apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-terminal
  namespace: nogoo9
  labels:
    nogoo9/pod-template: "true"
  annotations:
    nogoo9/description: "Interactive web terminal in the workspace sandbox with S3 sync"
    nogoo9/tag: "terminal"
    nogoo9/workspace-port: "7681"
    nogoo9/workspace-path: "/"
    nogoo9/api.terminal.port: "7681"
    nogoo9/api.terminal.path: "/"
    nogoo9/api.terminal.desc: "ttyd Web Terminal"
    nogoo9/required-context: "AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_ENDPOINT_URL,S3_BUCKET,S3_FOLDER"
    nogoo9/init-image: "nogoo9-registry.localhost:5001/amazon/aws-cli:latest"
    nogoo9/init-command: "aws s3 sync s3://$S3_BUCKET/$S3_FOLDER/${{user}} /workspace --endpoint-url $AWS_ENDPOINT_URL"
    nogoo9/pre-stop-command: "aws s3 sync /workspace s3://$S3_BUCKET/$S3_FOLDER/${{user}} --endpoint-url $AWS_ENDPOINT_URL"
    nogoo9/pre-stop-sidecar-image: "nogoo9-registry.localhost:5001/amazon/aws-cli:latest"
    nogoo9/default-grace-period: "15"
data:
  spec: |
    {
      "containers": [{
        "name": "agent",
        "image": "nogoo9-registry.localhost:5001/tsl0922/ttyd:latest",
        "command": ["ttyd", "-W", "-p", "7681", "/bin/sh"],
        "volumeMounts": [{"name": "workspace", "mountPath": "/workspace"}]
      }],
      "volumes": [{"name": "workspace", "emptyDir": {}}]
    }
