$schema: 'https://moonrepo.dev/schemas/project.json'

language: 'bash'
layer: 'tool'

tasks:
  bootstrap:
    command: './bootstrap.sh'
    options:
      cache: false
      runInCI: false

  start:
    command: 'k3d cluster start nogoo-dev'
    options:
      cache: false
      runInCI: false

  teardown:
    command: './teardown.sh'
    options:
      cache: false
      runInCI: false
