name: Deploy docs to GitHub Pages

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .prototools

      - name: Install dependencies
        run: bun install

      - name: Build docs
        run: bun run docs:build

      - name: Setup Pages
        uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc60fd9336d9342790937a514d0263f33cc2d # v3.0.1
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db901624e682285122765360673431620c3d9a # v4.0.5
